export enum OBSERVATION_VALUE {
  NEVER = 'NEVER',
  A_FEW_TIMES = 'A_FEW_TIMES',
  SOMETIMES = 'SOMETIMES',
  FREQUENTLY = 'FREQUENTLY',
  ALWAYS = 'ALWAYS',
}

export enum GENDER {
  MASCULINO = 'MALE',
  FEMENINO = 'FEMALE',
}

export enum SUBJECT_QUALIFICATION_VALUE {
  NOT_ENOUGH = 'NOT_ENOUGH',
  ENOUGH = 'ENOUGH',
  GOOD = 'GOOD',
  VERY_GOOD = 'VERY_GOOD',
  EXCELLENT = 'EXCELLENT',
}
