const form_data = [
  {
    form_name: 'student',
  },
  {
    form_name: 'attendance',
  },
  {
    form_name: 'subject_qualification',
  },
  {
    form_name: 'subject_qualification_and_observations',
  },
  {
    form_name: 'profile',
  },
];

const action_data = [
  {
    action_name: 'create_student',
    form_id: 'form_id',
  },
  {
    action_name: 'update_profile',
    form_id: 'form_id',
  },
  {
    action_name: 'delete_student',
    form_id: 'form_id',
  },
  {
    action_name: 'create_attendance',
    form_id: 'form_id',
  },
  {
    action_name: 'update_attendance',
    form_id: 'form_id',
  },
  {
    action_name: 'delete_attendance',
    form_id: 'form_id',
  },
  {
    action_name: 'create_subject_qualification',
    form_id: 'form_id',
  },
  {
    action_name: 'update_subject_qualification',
    form_id: 'form_id',
  },
  {
    action_name: 'delete_subject_qualification',
    form_id: 'form_id',
  },
  {
    action_name: 'create_subject_qualification_and_observations',
    form_id: 'form_id',
  },
  {
    action_name: 'update_subject_qualification_and_observations',
    form_id: 'form_id',
  },
  {
    action_name: 'delete_subject_qualification_and_observations',
    form_id: 'form_id',
  },
];

const group_data: any = [
  {
    group_name: 'teachers',
    users: [],
    actions: [],
  },
  {
    group_name: 'students',
    users: [],
    actions: [],
  },
  {
    group_name: 'administrators',
    users: [],
    actions: [],
  },
];

const grade_data: any[] = [
  {
    level: 1,
    section: 'A',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: 1,
    section: 'A',
    shift: 'T',
    teachers: [],
    students: [],
  },
  {
    level: 1,
    section: 'B',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: 1,
    section: 'B',
    shift: 'T',
    teachers: [],
    students: [],
  },
  {
    level: 1,
    section: 'C',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: 1,
    section: 'C',
    shift: 'T',
    teachers: [],
    students: [],
  },
  {
    level: 2,
    section: 'A',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: 2,
    section: 'A',
    shift: 'T',
    teachers: [],
    students: [],
  },
  {
    level: 2,
    section: 'B',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: 2,
    section: 'B',
    shift: 'T',
    teachers: [],
    students: [],
  },
  {
    level: 2,
    section: 'C',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: 2,
    section: 'C',
    shift: 'T',
    teachers: [],
    students: [],
  },
  {
    level: 3,
    section: 'A',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: 3,
    section: 'A',
    shift: 'T',
    teachers: [],
    students: [],
  },
  {
    level: 3,
    section: 'B',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: 3,
    section: 'B',
    shift: 'T',
    teachers: [],
    students: [],
  },
  {
    level: 3,
    section: 'C',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: 3,
    section: 'C',
    shift: 'T',
    teachers: [],
    students: [],
  },
  {
    level: 4,
    section: 'A',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: 4,
    section: 'A',
    shift: 'T',
    teachers: [],
    students: [],
  },
  {
    level: 4,
    section: 'B',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: 4,
    section: 'B',
    shift: 'T',
    teachers: [],
    students: [],
  },
  {
    level: 4,
    section: 'C',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: 4,
    section: 'C',
    shift: 'T',
    teachers: [],
    students: [],
  },
  {
    level: 5,
    section: 'A',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: 5,
    section: 'A',
    shift: 'T',
    teachers: [],
    students: [],
  },
  {
    level: 5,
    section: 'B',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: 5,
    section: 'B',
    shift: 'T',
    teachers: [],
    students: [],
  },
  {
    level: 5,
    section: 'C',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: 5,
    section: 'C',
    shift: 'T',
    teachers: [],
    students: [],
  },
  {
    level: 6,
    section: 'A',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: 6,
    section: 'A',
    shift: 'T',
    teachers: [],
    students: [],
  },
  {
    level: 6,
    section: 'B',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: 6,
    section: 'B',
    shift: 'T',
    teachers: [],
    students: [],
  },
  {
    level: 6,
    section: 'C',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: 6,
    section: 'C',
    shift: 'T',
    teachers: [],
    students: [],
  },
  {
    level: 7,
    section: 'A',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: 7,
    section: 'A',
    shift: 'T',
    teachers: [],
    students: [],
  },
  {
    level: 7,
    section: 'B',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: 7,
    section: 'B',
    shift: 'T',
    teachers: [],
    students: [],
  },
  {
    level: 7,
    section: 'C',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: 7,
    section: 'C',
    shift: 'T',
    teachers: [],
    students: [],
  },
];

const subject_data: any[] = [
  { subject_name: 'Lengua', teachers: [] },
  { subject_name: 'Ciencies Sociales', teachers: [] },
  { subject_name: 'Matematica', teachers: [] },
  { subject_name: 'Ciencias Natutales', teachers: [] },
  { subject_name: 'Tecnologia', teachers: [] },
  { subject_name: 'Form. Etica y Ciud.', teachers: [] },
  { subject_name: 'Educacion Fisica', teachers: [] },
  { subject_name: 'Plasitca ', teachers: [] },
  { subject_name: 'Musica', teachers: [] },
  { subject_name: 'Observaciones', teachers: [] },
];
