const forms = [
  {
    form_name: 'student',
  },
  {
    form_name: 'attendance',
  },
  {
    form_name: 'subject_qualification',
  },
  {
    form_name: 'subject_qualification_and_observations',
  },
];

const actions = [
  {
    action_name: 'create_student',
    form_id: 'form_id',
  },
  {
    action_name: 'update_student',
    form_id: 'form_id',
  },
  {
    action_name: 'delete_student',
    form_id: 'form_id',
  },
  {
    action_name: 'create_attendance',
    form_id: 'form_id',
  },
  {
    action_name: 'update_attendance',
    form_id: 'form_id',
  },
  {
    action_name: 'delete_attendance',
    form_id: 'form_id',
  },
  {
    action_name: 'create_subject_qualification',
    form_id: 'form_id',
  },
  {
    action_name: 'update_subject_qualification',
    form_id: 'form_id',
  },
  {
    action_name: 'delete_subject_qualification',
    form_id: 'form_id',
  },
  {
    action_name: 'create_subject_qualification_and_observations',
    form_id: 'form_id',
  },
  {
    action_name: 'update_subject_qualification_and_observations',
    form_id: 'form_id',
  },
  {
    action_name: 'delete_subject_qualification_and_observations',
    form_id: 'form_id',
  },
];

const groups: any = [
  {
    group_name: 'teachers',
    users: [],
    actions: [],
  },
  {
    group_name: 'students',
    users: [],
    actions: [],
  },
  {
    group_name: 'administrators',
    users: [],
    actions: [],
  },
];

const grades: any[] = [
  {
    level: '1',
    section: 'A',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: '1',
    section: 'A',
    shift: 'T',
    teachers: [],
    students: [],
  },
  {
    level: '1',
    section: 'B',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: '1',
    section: 'B',
    shift: 'T',
    teachers: [],
    students: [],
  },
  {
    level: '1',
    section: 'C',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: '1',
    section: 'C',
    shift: 'T',
    teachers: [],
    students: [],
  },
  {
    level: '2',
    section: 'A',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: '2',
    section: 'A',
    shift: 'T',
    teachers: [],
    students: [],
  },
  {
    level: '2',
    section: 'B',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: '2',
    section: 'B',
    shift: 'T',
    teachers: [],
    students: [],
  },
  {
    level: '2',
    section: 'C',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: '2',
    section: 'C',
    shift: 'T',
    teachers: [],
    students: [],
  },
  {
    level: '3',
    section: 'A',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: '3',
    section: 'A',
    shift: 'T',
    teachers: [],
    students: [],
  },
  {
    level: '3',
    section: 'B',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: '3',
    section: 'B',
    shift: 'T',
    teachers: [],
    students: [],
  },
  {
    level: '3',
    section: 'C',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: '3',
    section: 'C',
    shift: 'T',
    teachers: [],
    students: [],
  },
  {
    level: '4',
    section: 'A',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: '4',
    section: 'A',
    shift: 'T',
    teachers: [],
    students: [],
  },
  {
    level: '4',
    section: 'B',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: '4',
    section: 'B',
    shift: 'T',
    teachers: [],
    students: [],
  },
  {
    level: '4',
    section: 'C',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: '4',
    section: 'C',
    shift: 'T',
    teachers: [],
    students: [],
  },
  {
    level: '5',
    section: 'A',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: '5',
    section: 'A',
    shift: 'T',
    teachers: [],
    students: [],
  },
  {
    level: '5',
    section: 'B',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: '5',
    section: 'B',
    shift: 'T',
    teachers: [],
    students: [],
  },
  {
    level: '5',
    section: 'C',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: '5',
    section: 'C',
    shift: 'T',
    teachers: [],
    students: [],
  },
  {
    level: '6',
    section: 'A',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: '6',
    section: 'A',
    shift: 'T',
    teachers: [],
    students: [],
  },
  {
    level: '6',
    section: 'B',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: '6',
    section: 'B',
    shift: 'T',
    teachers: [],
    students: [],
  },
  {
    level: '6',
    section: 'C',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: '6',
    section: 'C',
    shift: 'T',
    teachers: [],
    students: [],
  },
  {
    level: '7',
    section: 'A',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: '7',
    section: 'A',
    shift: 'T',
    teachers: [],
    students: [],
  },
  {
    level: '7',
    section: 'B',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: '7',
    section: 'B',
    shift: 'T',
    teachers: [],
    students: [],
  },
  {
    level: '7',
    section: 'C',
    shift: 'M',
    teachers: [],
    students: [],
  },
  {
    level: '7',
    section: 'C',
    shift: 'T',
    teachers: [],
    students: [],
  },
];

const subjects: any[] = [
  { subject_name: 'Lengua'.toLowerCase(), teachers: [] },
  { subject_name: 'Ciencias_Sociales'.toLowerCase(), teachers: [] },
  { subject_name: 'Matematica'.toLowerCase(), teachers: [] },
  { subject_name: 'Ciencias_Naturales'.toLowerCase(), teachers: [] },
  { subject_name: 'Tecnologia'.toLowerCase(), teachers: [] },
  { subject_name: 'Formacion_Etica_y_Ciudadana'.toLowerCase(), teachers: [] },
  { subject_name: 'Educacion_Fisica'.toLowerCase(), teachers: [] },
  { subject_name: 'Plasitca'.toLowerCase(), teachers: [] },
  { subject_name: 'Musica'.toLowerCase(), teachers: [] },
  { subject_name: 'Observaciones'.toLowerCase(), teachers: [] },
];

export default {
  forms,
  actions,
  groups,
  grades,
  subjects,
};
